# Generated by Django 5.0.1 on 2024-05-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="price",
        ),
        migrations.RemoveField(
            model_name="book",
            name="publication_date",
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
